### ISSUE TITLE
Doesn't fail on missing `rpipe.sum`

### ISSUE THREAD

**Issue by Parakleta** [eborisch/rpipe#2]
The `check_pipe` method should fail if the `rpipe.sum` file is missing.  I had a situation recently with the Microsoft Auth outage where writes into a OneDrive account were only intermittently successful and `rpipe` failed to notice that the chunk writes were failing as they occurred, but more importantly when the `rpipe.sum` file failed to be written `rpipe` told me that the transmission was successful and that the checksums matched, despite around 2/3rds of the chunks being missing.

Ideally it would be nice if `rpipe` could notice when an individual transmission failed and abort early, but at the very least it must not signal success at the end when there are missing pieces.

**Comment by Parakleta** [comment]
I added a test to ensure that the "TOTAL" record is found and raise an exception otherwise.  I haven't tested it yet.

**Comment by eborisch** [comment]
Do you have a patch to update these changes? I haven't used this code in quite a while, but I'm happy to look at pull requests.

**Comment by eborisch** [comment]
Thanks for the patch!
